### ISSUE TITLE
Add a default .gitignore

### ISSUE THREAD

**Issue by ckuijjer** [vijairamcharan/create-lambda-express#1]
It would be really awesome if a default .gitignore file would be added, excluding

```
node_modules
.build
.serverless
```

**Comment by ckuijjer** [comment]
Actually, I now see that there's a `template/.gitignore`. I've added the `.build` directory used by Webpack to it, see #2 

The `.gitignore` is there when I clone the repository and use it to create the starter, however when I use `yarn create lambda-express` it's missing, and `~/.config/yarn/global/node_modules/create-lambda-express/template` doesn't show the `.gitignore` file. Perhaps the package in the npm repository doesn't have it?

**Comment by vijairamcharan** [comment]
Thanks for reporting and analysing the issue. Working on a fix...

**Comment by vijairamcharan** [comment]
Fixed with commit 8433510758e86b91434b95020c3a4c9103caa160. Published to npm at version 1.1.1
